### ISSUE TITLE
Thanks and a comment or two

### ISSUE THREAD

**Issue by rgmcleod52** [tommy-vaux/Snapmaker_2_PCB_Milling_Process#2]
Thank you for the tutorial.  Like you, I have a SnapMaker (an A350) that I'm trying to use to make some simple PCB's.

Some comments:

- I am using KiCad for the schematic and board design and FlatCam for generating the cnc files.  Similar process to what you have outlined.
- When I generated the drill files I used the "Drilling Tool", not the "Isolation Routing" as you called out.  Not sure if that's because of the KiCad output, or difference in FlatCam software, just pointing it out.
- I have used the cnc files from FlatCam without removing and pasting in the G Code you mentioned.  Maybe the 4.7 version of Luban handles those commands better now.
- Since I'm using carpet tape to secure the board to my sacrificial board, I don't worry about running into the hold downs.

Changing Bits Is My Big Issue
- My big challenge occurs when it's time to change bits between isolation routing, drilling and board cutout.  As I learned the hard way, changing bits, then loading in a new cnc file to the SM and pressing the "Go to Work Origin" can trash a small drill bit instantly due to the difference in length between the V bit and the drill bit.  
- Since that first disaster, I write down the X and Y values for the Work Origin when I start the first operation and when I load the new bit and new cnc file I manually move the cnc head to those values (or as close as I can get to them) keeping the bit far above the work surface.  Once I have the X and Y values set, I move the head down to adjust for a proper Z value using the spacer card.  
- That seems to work ok, but sometimes the X or Y value is off by a few hundredths of a mm since manual adjustment will only move by 1/10th of a mm.
- One person suggested I issue a "G28" command to take the head back to a known position, but when I tried that between bits I was off by several mm in the Y direction.
- I had hoped that the Luban software would allow you to go to "X & Y Work Origin" and leave the head well above the work surface.  That would make the bit changing process much easier.

Again, thanks for taking the time to document all that you've done.  

Rick

**Comment by tommy-vaux** [comment]
Hi @rgmcleod52, thanks for your feedback, and sorry I didn't get back to you. I haven't done PCB milling with it since this was published so it may be out of date at this point, I just noticed a lack of documentation around it at the time so published what I'd done to get something to work. Glad to hear you found it helpful!

In reply to your comments, generally it seems the situation has improved and snapmaker accepts more generic gcode at this point. If you've got any specific updates you'd like me to add to the page please let me know, I've already updated the doc to reflect your feedback

Changing bits and constantly having to modify the work origin was a challenge for me too, I went through quite a few bits, hence why I ended up with the V-bit as it was generally more robust for isolation routing. I generally had to move the head up a bit manually as going to work origin then moving it would also be close enough to just about touch the material and therefore risk breaking the bit.
